### PR TITLE
Collaborative recommender analysis

### PR DESCRIPTION
**Pull request by florian**
After I fixed the bug where the collaborative recommender was being used with the unfiltered addon list, it was only able to make recommendations for about 8% of all users. This number seems too low, so there's a good chance that something is still not correct.

To make it easier to look for a potential bug, I created a minimal notebook that can be used to reproduce these results. The AMO whitelist is the only thing that's used for filtering here.

### CODE REVIEW

**Comment by florian** [comment]
I'll do some more analysis before this is ready for reviewing!

**Review by mlopatka — COMMENTED** [review]
This is a really valuable analysis Florian. I did not find anything wrong in terms of bugs. to me this means that our addons ecosystem is in a very sad place right now. this notebook will be very valuable moving forward. I leave the technical last-pass to Dexter.

**Review by Dexterp37 — APPROVED** [review]

**Comment by benmiroglio** [comment]
Leaving some comments per @mlopatka 's request. 

First of all: nice work @florian, this is a very detailed and accurate representation of the add-ons ecosystem in Release. If I understand correctly, the `whitelist` set contains WebExtensions listed on AMO, meaning that 8.4% of users in longitudinal have *only* WebExtensions installed, the vast majority having only 1 WebExtension.  

* This analysis aligns with the add-ons states tracked [here](https://metrics.mozilla.com/protected/bmiroglio/firefox-addons/_site/addonCounts-release-beta.html), which contains total counts and percentages of users with different add-on states over time. We also track add-on users that have at least one WebExtension installed and only Level 1 and Level 2 add-ons, which are candidates for Legacy -> WebExtension porting. **These charts paint a brighter picture for WebExtensions in Release.**

* This analysis also aligns with our general [OKR dashboard](https://sql.telemetry.mozilla.org/dashboard/add-on-okrs_1) for add-ons. 


I wouldn't consider the add-ons ecosystem "sad" **yet** since these percentages are showing upward trends and will spike in 57 (see Beta charts around the end of Sept. in the first link). The main concern is that the percentages will spike due to a decreasing denominator (i.e. total client count). AdBlock Plus (`{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}`) is also on the road to WebExtensionry which will cause a sigificant bump. The bummer for TAAR is that most eligible clients have only 1 WebExtension, which I imagine results in rather generic recommendations when using CF.

I'm happy to elaborate on any of the above. Please let me know if my deductions from the notebook are inaccurate.

**Comment by mlopatka** [comment]
Thank you benmiroglio. This is the sanity check I was looking for.

**Comment by florian** [comment]
Hey Ben, thanks a lot for the thorough review! Your comments are very helpful and much appreciated. Just one small correction:

> meaning that 8.4% of users in longitudinal have *only* WebExtensions installed

This is not completely correct. It means that 8.4% of users in longitudinal have at least one WebExtension installed. However, they are not required to *only* have WebExtensions installed, they may also use legacy addons at the same time.

**Pull request merged**
